[project]
site_name = "Zensical Documentation"
site_url = "https://pccompass.github.io/zensical-docs/"
repo_url = "https://github.com/pccompass/zensical-docs"

[nav]
home = "index.md"
sa_system_analysis = "SA_system_analysis.md"

[theme]
name = "material"

[plugins]
search = {}
